# Generated by Django 4.1.1 on 2022-09-11 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logos/venues/')),
                ('proof_of_registration', models.FileField(blank=True, null=True, upload_to='documents/venues/registration_files/')),
                ('established', models.DateField(blank=True, null=True)),
                ('add_line_1', models.CharField(blank=True, max_length=128, null=True)),
                ('add_line_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Venue',
                'verbose_name_plural': 'Event Venues',
                'ordering': ('name', 'established'),
                'unique_together': {('name', 'owner', 'established', 'city', 'state', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SeatSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('total_seats', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=250.0, max_digits=7)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues_app.venue')),
            ],
            options={
                'verbose_name': 'Seating Section',
                'verbose_name_plural': 'Seating Sections',
                'ordering': ('venue', 'name', '-created'),
                'unique_together': {('name', 'venue')},
            },
        ),
        migrations.CreateModel(
            name='VenueEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employee_type', models.CharField(choices=[('Manager', 'Manager'), ('Steward', 'Steward'), ('Security', 'Security'), ('Executive', 'Executive'), ('Trainee', 'Trainee')], default='Steward', max_length=32)),
                ('contract_type', models.CharField(choices=[('Contractual', 'Contractual'), ('Permanent', 'Permanent'), ('Intern', 'Intern')], default='Permanent', max_length=32)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues_app.venue')),
            ],
            options={
                'verbose_name': 'Venue Employee',
                'verbose_name_plural': 'Venue Employees',
                'ordering': ('venue', 'employee'),
                'unique_together': {('employee', 'venue')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('seat_number', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='Available', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues_app.seatsection')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ('section', 'seat_number'),
                'unique_together': {('seat_number', 'section')},
            },
        ),
    ]
